### ISSUE TITLE
🗃️ 데이터 추가/삭제/변경

### ISSUE THREAD

**Issue by KwonSeami** [Dev-FE-2/toy-project1-team1-intranet-project#18]
데이터 추가/삭제/변경 커밋은 이 이슈를 태깅해주세요.

예: users.json에 '김영희' 유저 정보를 추가할 때

**Comment by jurilee0** [comment]
데이터 활용 dummy 방식(.json)에서 firebase로 변경되어 이슈 닫습니다.
