### ISSUE TITLE
뒤로가기하면 /join/login 페이지로 이동되는 이슈

### ISSUE THREAD

**Issue by KwonSeami** [Dev-FE-2/toy-project1-team1-intranet-project#33]
어느 페이지에서든 발생하는 이슈같습니다.

메인페이지에서 공지사항 페이지로 접속 -> 뒤로가기 -> /join/login 페이지로 이동됨
메인페이지에서 부재신청 페이지로 접속 -> 뒤로가기 -> /join/login 페이지로 이동됨

**Comment by vgotu99** [comment]
join 페이지 URL 파라미터 사용으로 인해 라우터 설정에서 로그인과 회원가입 경로를 /join/login, /join/signup으로 사용했었습니다.
다만 /join 경로로 진입 시 /join/login 혹은 /join/signup으로 리다이렉트 되는 코드로 인해 발생했던 오류로 파악했고
URL 파라미터에서 쿼리 파라미터로 변경하여 경로를 핸들링하도록 했고 통일된 URL 경로로 변경되었으므로 라우터 설정 또한 진행하여 이슈 해결하였습니다.
