### ISSUE TITLE
검색 history 이슈

### ISSUE THREAD

**Issue by Hoonshi** [Dev-FE-2/toy-project1-team1-intranet-project#40]
## 검색 history 이슈
1. 초기 페이지(/Announcement)에서 검색어를 입력하면  page=1&search=검색어로 들어가집니다.
1-2 이후 뒤로가기를 누르면 page=1&search=검색어가 유지됩니다.

2. 초기 페이지에서 n번째 페이지를 누른 후, 검색어를 입력하면 page=1&search=검색어로 잘 들어가집니다.
2-1. 검색어로 들어간 후, 뒤로가기를 누르면 ?page=n으로 잘 나오게 됩니다. 그러나 다시 앞으로 가기를 누르면, 쿼리스트링은 page=1&search=사심로 바뀌지만, 초기페이지의 내용이 렌더링이 됩니다.

**Comment by jurilee0** [comment]
`feauture/Announcement-bugfix` 브랜치 확인 부탁 드립니다!
기대 동작 충족하나 helper-text의 렌더 픽스가 필요합니다 :)

**Comment by jurilee0** [comment]
슬랙으로 공유 드린 내용 코멘트 남겨놓습니다.

**[주요 변동점]**
1. updatePagination > updateHistoryFlag 플래그로 업데이트 할 수 있도록 변경
2. popstate >  earchInput.value 통해 업데이트
3. 과정에서 updateHistory > url이 [오브젝트 오브젝트]로 반환되어서, encodeURIComponent로 문자열 변환 시도했습니다!

**[추가 확인사항]**
helper-text 렌더 시점 조절 픽스 필요하며,
AI를 의존이 높은 raw code기 때문에 전반적인 주석, 불필요한 구문 정리 진행해주시면 감사하겠습니다!
