### ISSUE TITLE
✨[관리자] 직원 목록

### ISSUE THREAD

**Issue by jurilee0** [Dev-FE-2/toy-project1-team1-intranet-project#7]
## 기능이름
직원 목록 페이지 구현

## 기능명
- [x] 직원 목록 데이터 바인딩
- [x] 근무 상태 UI 반응형 기능 추가
- [x] 유저 데이터 기반으로 사용자 근무 상태 변환 기능 추가

## 기능이름
직원 상세 페이지 구현

## 기능명
- [x] 직원 정보 데이터 바인딩
- [x] 직원 정보 수정 모달 추가
- [x] 직원 정보 수정 모달에서 가입 승인(소속, 직급 미부여 시 불가능)
- [x] 직원 정보 수정 모달에서 직원 정보 삭제 기능 추가
ㅤ => firebase authenticatin이 제공하는 계정 삭제 기능을 현재 개발 진행중인 프로젝트에 추가할 수 없는 이슈 발생
ㅤ => 삭제를 희망하는 계정의 firestore database 문서에 "isDeleted: true" 필드 추가 
ㅤ => 삭제된 계정으로 로그인 진행 시 이용이 불가능 에러 메시지 출력되도록 변경
- [x] 위 이슈 해결
- [x] "isDeleted: true"인 계정 렌더 XX -> 렌더 스타일 변경 (위 이슈 연장)
- [x] 비밀번호 재설정 메일 발송 기능 추가
- [x] #41
- [x] ㄴ> 쿼리 파라미터로 재 구현
- [x] 검색 구현

## 기간
~ 2024.10.30

**Comment by vgotu99** [comment]
직원 목록 페이지 구현 완료
